[workspace]
resolver = "2"
members = ["bot", "db", "server", "cli"]

[workspace.dependencies]
sqlx = { version = "0.6", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "migrate",
    "offline",
    "json",
] }
dotenv = "0.15"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.14.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
pr-run-mode = "plan"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
