[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Generate and dist a source tarball
source-tarball = false
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]

[dist.github-custom-runners]
global = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-22.04"
